apiVersion: v1
kind: Service
metadata:
  name: constellation-engine
  namespace: constellation
  labels:
    app.kubernetes.io/name: constellation-engine
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: constellation-engine
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
